@startuml диаграмма And_Xor
|Клиент|
start
if (Есть регистрация в системе?) then (да)
  :Вход в личный кабинет;
else (нет)
  :Регистрация;
endif
|Система|
:Авторизация кдиента в системе;
|Клиент|
:Выбор товаров и добавление в корзину;
:Оформление заказа;

|Система|
repeat
    :Проверка наличия товара;
    if (Товар в наличии?) then (да)
    break
    endif
    ->нет;
    :Уведомление клиента о недоступности товара;
    repeat while (Клиент выбрал альтернативный товар?) is (да) not (нет)
|Система|
:Заказ оформлен;
|Система|
  fork
    :Запрос оплаты;
    |Клиент|
    :Выбор способа оплаты;
    |Система|
    :Проверка платежных данных;
    if (Оплата прошла успешно?) then (нет) 
        if ( Недостаточно средств) then (да) 
        :Уведомление "Недостаточно средств";
        else (нет)
        endif
            if ( Неверные платёжные данные) then (да) 
            :Уведомление "Неверные платёжные данные";
            else (нет)
            :Уведомление "Платёжная система недоступна";
            endif
            |Клиент|
      if (Изменить платежные данные?) then (нет)
        |Система|
        :Отмена заказа;
        stop
        else (да)
        :Повторная попытка оплаты;
        endif
        else (да)     
    endif
    :Перевод заказа в статус «Оплачен»; 



  fork again
    |Система|
    :Уведомление склада собрать заказ;
    |Склад|
    :Сборка заказа;
    |Система|
  end fork

  :Генерация счета-фактуры;
  :Отправка уведомления клиенту о подтверждении заказа и статусе доставки;
  :Перевод заказа в статус «Отправлен»;

  |Клиент|
  :Отслеживание и получение уведомлений о доставке;

stop
@enduml
